org: linnjoha
app: bonzaiapiapp
service: bonzaiapi

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [BookingTable, Arn]
            - Fn::GetAtt: [RoomsTable, Arn]
            - Fn::Join:
                - ""
                - - Fn::GetAtt: [RoomsTable, Arn]
                  - /index/availableStatusIndex
  environment:
    BOOKING_TABLE: ${self:custom.tables.BookingTable}
    ROOMS_TABLE: ${self:custom.tables.RoomsTable}

custom:
  tables:
    BookingTable: "BookingTable-${sls:stage}"
    RoomsTable: "RoomsTable-${sls:stage}"

package:
  individually: true

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /bookroom
          method: POST
        events:
      - httpApi:
          path: /cancelbooking/{bookingId}
          method: DELETE
      - httpApi:
          path: /update
          method: PUT
      - httpApi:
          path: /allbookings
          method: GET

resources:
  Resources:
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.BookingTable}
        AttributeDefinitions:
          - AttributeName: bookingId
            AttributeType: S
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    RoomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.RoomsTable}
        AttributeDefinitions:
          - AttributeName: roomId
            AttributeType: S
          - AttributeName: availableStatus
            AttributeType: S
        KeySchema:
          - AttributeName: roomId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: availableStatusIndex
            KeySchema:
              - AttributeName: availableStatus
                KeyType: HASH
            Projection:
              ProjectionType: ALL
