org: linnjoha
app: bonzaiapiapp
service: bonzaiapi

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [BookingTable, Arn]
            - Fn::GetAtt: [RoomsTable, Arn]
  environment:
    BOOKING_TABLE: ${self:custom.tables.BookingTable}
    ROOMS_TABLE: ${self:custom.tables.RoomsTable}

custom:
  tables:
    BookingTable: "BookingTable-${sls:stage}"
    RoomsTable: "RoomsTable-${sls:stage}"

package:
  individually: true

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /bookroom
          method: POST

resources:
  Resources:
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.BookingTable}
        AttributeDefinitions:
          - AttributeName: bookingId
            AttributeType: S
          - AttributeName: inDate
            AttributeType: S
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH
          - AttributeName: inDate
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: inDateIndex
            KeySchema:
              - AttributeName: inDate
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    RoomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.RoomsTable}
        AttributeDefinitions:
          - AttributeName: roomId
            AttributeType: S
          - AttributeName: availableStatus # Change from isAvailable (BOOL) to String (S)
            AttributeType: S
        KeySchema:
          - AttributeName: roomId
            KeyType: HASH
          - AttributeName: availableStatus # Change this key to match the new String attribute
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: availableStatusIndex # New GSI to track room availability
            KeySchema:
              - AttributeName: availableStatus
                KeyType: HASH
            Projection:
              ProjectionType: ALL
