org: johan1
service: BonzaiAPI

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [BookingTable, Arn]
            - Fn::GetAtt: [RoomsTable, Arn]
  environment:
    BOOKING_TABLE: ${self:custom.tables.BookingTable}
    ROOMS_TABLE: ${self:custom.tables.RoomsTable}

custom:
  tables:
    BookingTable: "BookingTable-${sls:stage}"
    RoomsTable: "RoomsTable-${sls:stage}"

package:
  individually: true

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: /all
        method: GET

resources:
  Resources:
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.BookingTable}
        AttributeDefinitions:
          - AttributeName: bookingId
            AttributeType: S
          - AttributeName: mail
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: inDate
            AttributeType: S
          - AttributeName: outDate
            AttributeType: S
          - AttributeName: totalGuests
            AttributeType: N
          - AttributeName: totalCost
            AttributeType: N
          - AttributeName: bookedRoom
            AttributeType: SS
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    RoomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.RoomsTable}
        AttributeDefinitions:
          - AttributeName: roomId
            AttributeType: S
          - AttributeName: roomType
            AttributeType: S
          - AttributeName: price
            AttributeType: N
          - AttributeName: maxPerRoom
            AttributeType: N
          - AttributeName: isAvailable
            AttributeType: BOOL
        KeySchema:
          - AttributeName: roomId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
